package com.phantomwing.eastersdelight.villager;

/**
 * 26.1: fabric-api removed {@code TradeOfferHelper} entirely; trades are now data-driven via
 * {@link net.minecraft.world.item.trading.VillagerTrade} JSON files in
 * {@code data/<namespace>/villager_trade/}, grouped into {@link net.minecraft.tags.TagKey} pools
 * referenced from {@link net.minecraft.world.item.trading.TradeSet} JSON in
 * {@code data/<namespace>/trade_set/}, and wired to the profession through
 * {@link net.minecraft.world.entity.npc.villager.VillagerProfession}'s {@code tradeSetsByLevel}.
 *
 * <p>The actual Egg Bunny trades are now generated by
 * {@link com.phantomwing.eastersdelight.datagen.ModVillagerTrades} and
 * {@link com.phantomwing.eastersdelight.datagen.ModVillagerTradeTagsProvider} via
 * {@code runDatagen}; this runtime stub is kept so {@link com.phantomwing.eastersdelight.EastersDelight}
 * can still call a {@code register()} hook for symmetry with the other registries.
 */
public class ModVillagerTrades {
    public static float EMERALD_MULTIPLIER = 0.2f;

    public static void register() {
        // No-op: trades live in JSON now. See class javadoc and datagen provider.
    }
}
