package com.phantomwing.eastersdelight;

import com.phantomwing.eastersdelight.block.ModBlocks;
import com.phantomwing.eastersdelight.component.ModDataComponents;
import com.phantomwing.eastersdelight.item.ModItems;
import com.phantomwing.eastersdelight.recipe.ModRecipes;
import com.phantomwing.eastersdelight.screen.ModMenuTypes;
import com.phantomwing.eastersdelight.itemGroup.ModItemGroups;
import com.phantomwing.eastersdelight.villager.ModVillagerTrades;
import com.phantomwing.eastersdelight.villager.ModVillagers;
import com.phantomwing.eastersdelight.util.ComposterHelper;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.resource.ResourceManagerHelper;
import net.fabricmc.fabric.api.resource.ResourcePackActivationType;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.resources.Identifier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EastersDelight implements ModInitializer {
    public static final String MOD_ID = "eastersdelight";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        // Register the config file.
        EastersDelightConfig.register();

        // Items
        ModItems.register();
        ModBlocks.register();
        ModDataComponents.register();
        ModRecipes.register();

        // UI
        ModItemGroups.register();
        ModMenuTypes.register();

        // Villagers
        ModVillagers.register();
        ModVillagerTrades.register();

        // Misc
        ComposterHelper.register();

        // Register a built-in resource pack that overrides FDR's baked_cod_stew and noodle_soup
        // recipes. Fabric Loader sorts regular mod packs alphabetically by mod ID, so
        // "farmersdelight" beats "eastersdelight" and any data/farmersdelight/… file we ship in
        // our main resources gets ignored at runtime. Built-in packs registered through Fabric
        // Resource Loader sit above the regular mod-pack stack, so files inside them take
        // precedence. The pack's content is generated by ModFarmersDelightOverrideRecipeProvider.
        FabricLoader.getInstance().getModContainer(MOD_ID).ifPresent(container ->
                ResourceManagerHelper.registerBuiltinResourcePack(
                        Identifier.fromNamespaceAndPath(MOD_ID, "farmersdelight_overrides"),
                        container,
                        ResourcePackActivationType.ALWAYS_ENABLED
                )
        );
    }
}
